create database assignment1;

CREATE TABLE Workers (
    WORKER_ID INT PRIMARY KEY,
	FIRST_NAME CHAR(25) NOT NULL,
	LAST_NAME CHAR(25),
	SALARY int CHECK (salary Between 10000 and 25000),
	JOINING_DATE DATETIME,
	DEPARTMENT CHAR(25) CHECK(Department in('IT','Sales','HR','Accounts')),
);

INSERT INTO workers (WORKER_ID, FIRST_NAME,LAST_NAME, SALARY, JOINING_DATE , DEPARTMENT)
VALUES
(1, 'Chirag', 'Kapadiya', 15000 ,'2016-06-15 00:00:00', 'IT'),
(2, 'Saurav', 'Tandon', 11000, '2022-10-25 00:00:00', 'Sales'),
(3, 'Animesh', 'Pandey', 18000, '2006-07-30 00:00:00', 'HR')

INSERT INTO workers (WORKER_ID, FIRST_NAME,LAST_NAME, SALARY, JOINING_DATE , DEPARTMENT)
VALUES
(4, 'abc', 'xyz', 24000 ,'2013-12-12 00:00:00', 'IT'),
(5, 'pqr', 'mno', 20000, '2022-10-25 00:00:00', 'Accounts'),
(6, 'efg', 'hij', 11000, '2024-01-01 00:00:00', 'HR')

SELECT FIRST_NAME AS WORKER_NAME FROM Workers;

SELECT upper(FIRST_NAME) FROM Workers;

SELECT DISTINCT DEPARTMENT FROM Workers;

SELECT LEFT(FIRST_NAME, 3) FROM Workers;

SELECT CHARINDEX('a' , FIRST_NAME) AS 'Position of a' 
FROM Workers 
WHERE FIRST_NAME = 'Chirag';

SELECT rtrim(FIRST_NAME) FROM Workers;

SELECT ltrim(DEPARTMENT) FROM Workers;

SELECT DISTINCT LEN(DEPARTMENT) as length,DEPARTMENT FROM Workers;

SELECT REPLACE(FIRST_NAME, 'a', 'A')
FROM Workers;

SELECT CONCAT(FIRST_NAME, '', LAST_NAME) AS Full_name
FROM Workers;

SELECT *
FROM Workers
ORDER BY FIRST_NAME ASC;

SELECT *
FROM Workers
ORDER BY FIRST_NAME ASC, DEPARTMENT DESC;


SELECT *
FROM Workers
WHERE FIRST_NAME IN ('Chirag', 'Saurav');

SELECT *
FROM Workers
WHERE FIRST_NAME NOT IN ('Chirag', 'Saurav');

SELECT *
FROM Workers
WHERE DEPARTMENT = 'IT';

SELECT *
FROM Workers
WHERE FIRST_NAME LIKE '%a%';

SELECT *
FROM Workers
WHERE FIRST_NAME LIKE '%a';

SELECT *
FROM Workers
WHERE FIRST_NAME LIKE '______h';

SELECT *
FROM Workers
WHERE MONTH(JOINING_DATE) = 2 AND YEAR(JOINING_DATE) = 2014;

SELECT COUNT(*)
FROM Workers
WHERE DEPARTMENT = 'IT';